/**
 * 头像地址生成（DiceBear 兼容协议）
 *
 * 头像不再使用固定的图片外链，而是按「稳定 seed」实时生成矢量头像：
 *   {AVATAR_BASE_URL}/{style}/svg?seed={seed}
 *
 * 外网版（默认）：https://api.dicebear.com/10.x/adventurer/svg?seed=7462200
 * 内网版（部署时切换）：http://10.9.43.61:4987/9.x/adventurer/svg?seed=zhang.san123
 *
 * 关键设计：**host 与版本号只存在于配置里，不写死在业务代码**。
 * base 里带版本段（`10.x` / `9.x`），内网自建服务版本与官方不一致时也只需改配置。
 * 另外 reconcileAvatarUrl 会在启动时把「历史自动生成的头像」重写到当前 base，
 * 所以从外网切内网只需改 AVATAR_BASE_URL 后重启，不需要写数据迁移脚本。
 */

/** 官方公共服务，作为未配置时的缺省值 */
export const DEFAULT_AVATAR_BASE_URL = 'https://api.dicebear.com/10.x';

/** 缺省头像风格（内网服务同样提供该风格） */
export const DEFAULT_AVATAR_STYLE = 'adventurer';

/**
 * 历史遗留的头像外链前缀：这些是早期硬编码的 Unsplash 人像图。
 * 启动期 reconcile 时一并重写成 DiceBear 头像，避免新旧两套风格混杂。
 */
const LEGACY_AVATAR_PREFIXES = ['https://images.unsplash.com/'];

/** 读取头像服务 base（去掉尾部斜杠，便于拼接） */
export function resolveAvatarBaseUrl(): string {
  const raw = (process.env.AVATAR_BASE_URL || '').trim();
  return (raw || DEFAULT_AVATAR_BASE_URL).replace(/\/+$/, '');
}

/** 读取头像风格 */
export function resolveAvatarStyle(): string {
  const raw = (process.env.AVATAR_STYLE || '').trim();
  return raw || DEFAULT_AVATAR_STYLE;
}

/**
 * 按 seed 生成头像 URL
 * @param seed 稳定标识（同一个人必须始终得到同一个 seed，否则头像会变脸）
 */
export function buildAvatarUrl(seed: string): string {
  const safeSeed = encodeURIComponent((seed || 'anonymous').trim() || 'anonymous');
  return `${resolveAvatarBaseUrl()}/${resolveAvatarStyle()}/svg?seed=${safeSeed}`;
}

/**
 * 从用户身份里挑选稳定 seed
 *
 * 优先级：工号 → 登录名 → 邮箱 → 姓名。
 * 工号优先是因为它是本系统的主登录标识且终身不变；姓名放最后（会重名、会改）。
 */
export function resolveAvatarSeed(identity: {
  employeeId?: string | null;
  loginName?: string | null;
  email?: string | null;
  name?: string | null;
}): string {
  return (
    identity.employeeId?.trim() ||
    identity.loginName?.trim() ||
    identity.email?.trim() ||
    identity.name?.trim() ||
    'anonymous'
  );
}

/** 按用户身份直接生成头像 URL */
export function buildUserAvatarUrl(identity: {
  employeeId?: string | null;
  loginName?: string | null;
  email?: string | null;
  name?: string | null;
}): string {
  return buildAvatarUrl(resolveAvatarSeed(identity));
}

/**
 * 判断一个头像地址是否为「系统自动生成/ 历史遗留」的
 *
 * 只有这类地址才允许在启动期被重写；用户自己上传或手填的头像必须原样保留。
 * 判定方式：命中历史 Unsplash 前缀，或符合 DiceBear 的 `/<style>/svg?seed=` 形态
 * （不限 host —— 正是为了识别出「上一次部署用的是另一个 host」的旧数据）。
 */
export function isAutoGeneratedAvatar(url?: string | null): boolean {
  const value = (url || '').trim();
  if (!value) return false;
  if (LEGACY_AVATAR_PREFIXES.some((prefix) => value.startsWith(prefix))) {
    return true;
  }
  return /\/[a-z0-9-]+\/svg\?seed=/i.test(value);
}

/**
 * 把自动生成的头像重写到当前配置的 base
 * @returns 需要更新时返回新地址；无需变更时返回 null
 */
export function reconcileAvatarUrl(
  current: string | null | undefined,
  identity: {
    employeeId?: string | null;
    loginName?: string | null;
    email?: string | null;
    name?: string | null;
  },
): string | null {
  // 空头像也补齐：老数据里存在 '' 的快照字段
  if (current && !isAutoGeneratedAvatar(current)) return null;
  const expected = buildUserAvatarUrl(identity);
  return current === expected ? null : expected;
}
